name: Auto-assign Copilot to Issues

on:
  issues:
    types: [opened]

# Set permissions for the workflow
permissions:
  issues: write
  contents: read

jobs:
  assign-copilot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Assign Copilot to issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            
            console.log(`🔄 Attempting to assign Copilot to issue #${issueNumber}`);
            
            try {
              // Add Copilot as assignee
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                assignees: ['Copilot']
              });
              
              console.log(`✅ Successfully assigned Copilot to issue #${issueNumber}`);
              
              // Also add a comment to confirm the assignment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: '🤖 **Copilot has been automatically assigned to this issue.**\n\nI\'ll help you implement this feature! Feel free to ask questions or request guidance on the implementation approach.'
              });
              
            } catch (error) {
              console.log(`⚠️ Could not assign Copilot to issue #${issueNumber}:`, error.message);
              
              // Add a comment explaining the limitation
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: '⚠️ **Unable to automatically assign Copilot to this issue.**\n\nThis may be due to:\n- Repository settings or permissions\n- Copilot availability in this repository\n- GitHub API limitations\n\nPlease manually assign Copilot or another team member if needed.'
              });
            }